# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true
workspace 'NLiteAVDemo'
source 'https://github.com/CocoaPods/Specs.git'

# There are no targets called "Shows" in any Xcode projects
abstract_target 'NEPkDemo' do

  pod 'NERtcSDK', '4.2.115'
  pod 'NIMSDK_LITE', '8.6.2'
  
  target 'NLiteAVDemo' do
    use_frameworks!
    pod 'Nama-lite', '7.3.2'
    pod 'Masonry'
    pod 'SDWebImage', '5.11.1'
    pod 'Toast'
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'M80AttributedLabel', '~> 1.3.1'
    pod 'NELivePlayer', '2.8.0'
    pod 'IQKeyboardManager', '~> 6.5.6'
    pod 'ReactiveObjC', '~> 3.1.0'
    pod 'Reachability'
    pod 'YXAlog_iOS', '~> 0.1.0'
    pod 'BlocksKit'
    pod 'YXLogin', '1.0.0'
#    pod 'YXLogin', :path => '../YXLogin/'
#    pod 'YXLogin', :git => 'ssh://git@g.hz.netease.com:22222/yunxin-app/yunxin-login-ios.git', :branch => 'login/1.0.0'

  end

  target 'NELiveRoom' do
    project './NELiveRoom/NELiveRoom.xcodeproj'
    end



end
