# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NLiteAVDemo' do
  use_frameworks!

pod 'NERtcSDK', '~> 4.0.1'
pod 'Nama-lite', '7.1.2'
pod 'NIMSDK_LITE', '8.3.0'
pod 'Masonry'
pod 'SDWebImage', '~> 5.7.1'
pod 'Toast'
pod 'MJRefresh'
pod 'YYModel'
pod 'M80AttributedLabel', '~> 1.3.1'
pod 'NELivePlayer', '~> 2.7.1'
pod 'CocoaLumberjack', '~> 3.2.1'
pod 'IQKeyboardManager', '~> 6.5.6'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'Reachability'

end
